Nether:
 - '§4These are are the only rules in the Nether'
 - '§4You are not safe in the Nether'
 - '§c#1 - Do as the admins say, always. We override the rules.'
 - '§c#2 - No hacking. No hacking clients. No hacking codes.'
 - '§c#3 - Chat rules apply. We can still hear you.'
 - '§c#4 - No traps near Nether Spawn. It`s annoying.'
 - '§c#5 - Don`t try to destroy server-builds (ie: Spawn).'
Rift:
 - '§cThe great Phanku made the Cubeville world, and it was good.'
 - '§cGoalieGuy6 and Inutterable came after,'
 - '§cand expanded the Cubeville.'
 - '§cThe Cubeville thrived, and was free of Notchings,'
 - '§cand the Cs were happy.'
 - '§cSuddenly, there was a great booming voice, from high above the Skylands, roaring down into the Nether and the End. "§4RIFT!"'
 - '§cGoalieGuy6 and Inutterable made §ba copy of the world§c as it was, so the ensuing Chaos would not render it Void."§4RIIIIIIFFT!"'
 - '§cThe battle began, and the world was rendered Null for a time. §4"RRRRRRRRRRRRRIIIIIIIIIIIFFFFFFFFFFTTTTTTTTTTTT"'
WhatIsRift:
 - '§cA breakdown of all friendly relations'
 - '§cA split from reality'
 - '§cChaos reigning over Cubeville'
Rules of Rift:
 - '§cNo swearing'
 - '§cNo complaining'
 - '§cNo mercy'
